[package]
name = "rt-in-1-weekend"
version = "0.1.0"
edition = "2021"

[dependencies]
glam="0.21.3"
#serde="1"
#serde_json="1.0.41"
#serde_derive="1"
image = "0.24.3"
#num-traits = "0.2.8"
#num-complex = "0.2.0"
termion="1.5.3"